# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7PC5fsjR03hJ4C2tBE4J3PaTh8_QFV8

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

g.add((ns.University, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""[texto del enlace](https://)**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

g.add((ns.Researcher ,RDFS.subClassOf, ns.Person))
for s, p, o in g:
  print(s,p,o)

"""[texto del enlace](https://)**TASK 6.3: Create a new individual of Researcher named "Jane Smithers"**"""

janeURI = ns.JaneSmithers
g.add((janeURI,RDF.type,ns.Researcher))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmithers the email address, fullName, given and family names. Use the https://schema.org vocabulary**"""

email=Literal("janeSmiters@gmail.course_materia")
fullname=Literal("Jane Smithers")
givename=Literal("Jane")
familyname=Literal("Smithers")
SCHEMA=Namespace("https://schema.org/Person")
g.add((janeURI,SCHEMA.FN,fullname))
g.add((janeURI,SCHEMA.email,email))
g.add((janeURI,SCHEMA.givename,givename))
g.add((janeURI,SCHEMA.familyname,familyname))
for s,p,o in g:
  print(s,p,o)

"""**TASK 6.5: Add UPM as the university where John Smith works. Use the "https://example.org/ namespace**"""

EX=Namespace("https://example.org/")
UPM=EX.UPM
g.add((UPM,RDF.type, ns.University))
g.add((ns.JohnSmith, EX.worksat,UPM))
for s,p,o in g:
  print(s,p,o)

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary. Make sure the relationship exists.**"""

FOAF=Namespace("http://xmlns.com/foaf/spec/")
g.add((ns.JohnSmith,FOAF.knows,janeURI))
for s,p,o in g:
  print(s,p,o)